Feature/add GitHub actions
codex-team/ctproto pull request #2
Opened 2020-12-15 23:49 UTC by fabled228

2020-12-16 12:32 UTC, talyguryn requested changes

2020-12-16 12:32 UTC, talyguryn commented on .github/workflows/npm-publish.yml
> +          webhook: ${{ secrets.CODEX_BOT_WEBHOOK_HAWK }}
```suggestion
          webhook: ${{ secrets.CODEX_BOT_WEBHOOK_DEVOPS_TOOLBOX }}
```

2020-12-21 21:05 UTC, talyguryn requested changes

2020-12-21 21:05 UTC, talyguryn commented on .github/workflows/npm-publish.yml
> +      - run: yarn lint:fix
it is not okay. you should use "fix" option locally before committing. action must **test** linting before building and publishing

2020-12-21 21:32 UTC, neSpecc approved these changes

2020-12-22 10:36 UTC, talyguryn approved these changes

2020-12-22 10:39 UTC, merged