Feature/ct proto client
codex-team/ctproto pull request #3
Opened 2020-12-17 18:25 UTC by kebyo

Added CTProtoClient

2020-12-18 18:41 UTC, ilyamore88 commented on src/client/client.ts
> +      if (messageId == null) {
```suggestion
      if (messageId === null) {
```

2020-12-19 21:19 UTC, neSpecc commented on src/client/client.ts
> +  onAuth: (data: ApiResponse) => Promise<void> | void;
а тут более конкретно тип можно указать?

2020-12-19 21:19 UTC, neSpecc commented on src/client/client.ts
> +   * Allows to disable validation/authorization and other warning messages
```suggestion
   * Allows disabling logs
```

2020-12-19 21:19 UTC, neSpecc commented on src/client/client.ts
> +        request.cb(message);
может туда paylod только передать?

2020-12-19 21:19 UTC, neSpecc commented on src/client/client.ts
> +    this.requests.push({
тут я бы добавил проверку на наличие `cb` (`typeof cb === 'function'`). Вдруг будут запросы, которым не нужен ответ — они просто не будут передавать `cb` и память не будет утекать

2020-12-19 21:19 UTC, neSpecc commented on src/client/client.ts
> +        } else if (this.socket.readyState === this.socket.OPEN) {
может в эту проверку (с обратным знаком) обернуть вызов `this.waitForOpenConnection` ?
а то он на каждое сообщение будет создавать интервал

2020-12-19 21:19 UTC, neSpecc commented on src/client/client.ts
> +      request: JSON.parse(message),
точно надо после `JSON.stringify` сразу делать `JSON.parse`? точно нам надо хранить `type` и `payload`? может достаточно только `messageId`?

Ведь мы и так знаем type и payload на момент вызова (то есть в `response` их передавать не нужно)

```js
transport.send('some-request', { somePayload }).then((response) => ...)
```

2020-12-19 21:19 UTC, neSpecc commented on src/client/client.ts
> +      cb,
Кстати можно попробовать возвращать промис:

```js
return new Promise((resolve, reject) => {
   // ...
   this.requests.push({
     messageId: message.id,
     cb(response){
       resolve(response)
     }
  })
  // ...
})
```

2020-12-20 08:58 UTC, kebyo commented on src/client/client.ts
> +      request: JSON.parse(message),
Если даже хранить только `messageId`, то без `JSON.parse` мы не получим же `messageId`

2020-12-21 16:32 UTC, kebyo commented on src/client/client.ts
> +        request.cb(message);
fixed

2020-12-21 16:33 UTC, kebyo commented on src/client/client.ts
> +    this.requests.push({
fixed

2020-12-21 16:33 UTC, kebyo commented on src/client/client.ts
> +  onAuth: (data: ApiResponse) => Promise<void> | void;
fixed

2020-12-21 19:25 UTC, ilyamore88 commented on src/client/client.ts
> + *  @template AuthRequestPayload - data used for authorization
```suggestion
 * @template MessagePayload - what kind of data passed with the message
 * @template AuthRequestPayload - data used for authorization
```

2020-12-21 19:25 UTC, ilyamore88 commented on src/client/client.ts
> +       * if messageId == null then this message inited by the API
```suggestion
       * if messageId === null then this message inited by the API
```

2020-12-21 19:28 UTC, ilyamore88 approved these changes

2020-12-21 21:19 UTC, neSpecc requested changes

2020-12-21 21:19 UTC, neSpecc commented on example/index.ts
> +    return {
при неуспешной авторизации onAuth должен выбросить ошибку

2020-12-21 21:19 UTC, neSpecc commented on example/index.ts
> +type Payload = Record<string, string>
какая-то каша без доков

2020-12-21 21:19 UTC, neSpecc commented on example/index.ts
> +const client = new CTProtoClient<Payload, AuthorizeMessagePayload, ApiResponse>({
может разнести на example/client.ts и example/server.ts и в index.ts их импортировать?

2020-12-21 21:19 UTC, neSpecc commented on src/client/client.ts
> +      this.log('Error');
непонятный текст ошибки. Надо написать подробнее, где Error + добавить текст ошибки в лог

2020-12-21 21:19 UTC, neSpecc commented on src/client/client.ts
> +    this.socket.onmessage = (event) => {
не указан тип у event

2020-12-21 21:19 UTC, neSpecc commented on src/client/client.ts
> +      const message: ApiResponse = JSON.parse(event.data.toString());
JSON.parse всегда надо заворачивать в try-catch

2020-12-21 21:19 UTC, neSpecc commented on src/client/client.ts
> +    if (this.socket.readyState === this.socket.CONNECTING) {
а если CLOSED?

2020-12-21 21:19 UTC, neSpecc commented on src/client/client.ts
> +        cb(response) {
надо описать тип `cb`, вынести его и указать и тут и в интерфейсе Request

2020-12-21 21:19 UTC, neSpecc commented on src/client/client.ts
> +  cb?: (payload: MessagePayload) => Promise<void> | void;
у тебя промис нигде не возвращается

2020-12-21 21:22 UTC, neSpecc requested changes

2020-12-21 21:22 UTC, neSpecc commented on example/index.ts
> +  onAuth: (data: Payload) => {
здесь должен быть более конкретный тип - AuthorizeMessagePayload

2020-12-21 21:23 UTC, neSpecc requested changes

2020-12-21 21:23 UTC, neSpecc commented on src/client/client.ts
> +  onAuth: (payload: MessagePayload) => Promise<void> | void;
тут тоже AuthRequestPayload

2020-12-21 21:27 UTC, neSpecc commented on example/index.ts
> +type Payload = Record<string, string>
лучше реализовать сразу более конкретный пример через [Discriminating Unions](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions), типа как в апи. Хотя бы два запроса через `|` описать

2020-12-21 21:34 UTC, neSpecc requested changes
Надо добавить readme к клиенту с инструкцией по использованию и примерами кода

2020-12-22 14:29 UTC, kebyo commented on src/client/client.ts
> +        } else if (this.socket.readyState === this.socket.OPEN) {
fixed

2020-12-22 15:55 UTC, kebyo commented on src/client/client.ts
> +      this.log('Error');
fixed

2020-12-22 15:55 UTC, kebyo commented on src/client/client.ts
> +    this.socket.onmessage = (event) => {
fixed

2020-12-22 15:55 UTC, kebyo commented on src/client/client.ts
> +      const message: ApiResponse = JSON.parse(event.data.toString());
fixed

2020-12-22 16:04 UTC, kebyo commented on src/client/client.ts
> +    if (this.socket.readyState === this.socket.CONNECTING) {
fixed

2020-12-22 16:27 UTC, kebyo commented on src/client/client.ts
> +  onAuth: (payload: MessagePayload) => Promise<void> | void;
Так нам же нужно обработать ответ авторизации, а `AuthRequestPayload` - данные для авторизации. Может тогда сделать что-то вроде AuthResponsePayload?

2020-12-22 16:37 UTC, ilyamore88 commented on package.json
> +    "run:example": "ts-node example/index.ts"
```suggestion
    "run:example": "ts-node example/index.ts",
```

2020-12-22 18:01 UTC, neSpecc requested changes

2020-12-22 18:01 UTC, neSpecc commented on src/client/client.ts
> +type Callback<MessagePayload> = (payload: MessagePayload) => void;
RequestCallback

2020-12-22 19:25 UTC, kebyo commented on src/client/client.ts
> +        cb(response) {
fixed

2020-12-22 20:39 UTC, kebyo commented on example/index.ts
> +const client = new CTProtoClient<Payload, AuthorizeMessagePayload, ApiResponse>({
Тогда у нас сервер по не будет запускаться, так как у него нет внешней логики, в отличие от клиента.

![image](https://user-images.githubusercontent.com/64841603/102931054-78240180-44bf-11eb-9ae7-1ad50b841ee1.png)

2020-12-22 20:40 UTC, kebyo commented on example/index.ts
> +const client = new CTProtoClient<Payload, AuthorizeMessagePayload, ApiResponse>({
Ну можно выводить клиентов и тогда сервер будет запускаться
`console.log(Server.clients)`

2020-12-22 20:40 UTC, kebyo commented on src/client/client.ts
> +  cb?: (payload: MessagePayload) => Promise<void> | void;
fixed

2020-12-22 20:43 UTC, neSpecc commented on src/client/client.ts
> +  onAuth: (payload: MessagePayload) => Promise<void> | void;
да

2020-12-22 20:45 UTC, neSpecc commented on example/index.ts
> +const client = new CTProtoClient<Payload, AuthorizeMessagePayload, ApiResponse>({
он будет запускаться так же как и сейчас, речь просто про перемещение кода

2020-12-22 20:46 UTC, neSpecc commented on example/index.ts
> +const client = new CTProtoClient<Payload, AuthorizeMessagePayload, ApiResponse>({
можешь сделать функцию createServer, экспортировать ее и вызвать

2020-12-23 06:34 UTC, neSpecc requested changes

2020-12-23 06:34 UTC, neSpecc commented on example/client.ts
> +  onMessage: (data: ApiResponse['payload']) => {
я думаю, что в onMessage все таки надо передавать целиком сообщение. Чтобы внутри можно было реализовать switch по типам. Это же "входящее", а не "ответ". В ответе — только payload ок

2020-12-23 10:38 UTC, neSpecc requested changes

2020-12-23 10:38 UTC, neSpecc commented on example/client.ts
> +  onMessage: (data: ApiResponse) => {
я думаю, надо разделить ApiResonse на два типа — `ApiResponse` и `ApiUpdate`. В данном случае будет ApiUpdate — инициированное бэкендом сообщение, адресованное клиенту

2020-12-24 11:11 UTC, ilyamore88 reviewed
В package.json необходимо поднять версию до 0.0.4, чтобы после мержа всё опубликовалось в npm.

2020-12-24 11:30 UTC, neSpecc approved these changes

2020-12-24 11:31 UTC, merged